### ISSUE TITLE
upon backpressing at addnewalarm fragment creating new record

### ISSUE THREAD

**Issue by shobhan1595** [PPartisan/Simple-Alarms#1]

**Comment by PPartisan** [comment]
This is expected behaviour - pressing the "Add New Alarm" FAB creates a new Alarm and immediately takes you to its Edit page.

**Comment by brittle123** [comment]
Why is this happening btw?,.. Can you please tell me how to resolve it!

**Comment by PPartisan** [comment]
There's nothing to resolve - it's how the app works.

If you want to change that behaviour, you can modify `AddEditAlarmActivity`. You can see in there that it creates a new Alarm entry as soon as the FAB is pressed on the Alarms list page:
```
private Alarm getAlarm() {
        switch (getMode()) {
            case ADD_ALARM:
                final long id = DatabaseHelper.getInstance(this).addAlarm();
                LoadAlarmsService.launchLoadAlarmsService(this);
                return new Alarm(id);
```
You'll just need to defer this until the Alarm is saved.

**Comment by brittle123** [comment]
Sir really appreciate your quick response but don't know how to defer this... Please can you tell me what to change in AddEditAlarmActivity and AddEditAlarmFragment classes. Because when i commented this case lines it shows error in the AddEditAlarmFragment class . Waiting for your response.
Thanks & Regards

**Comment by smfahadhassan** [comment]
You'll have to defer this code until the alarm is saved, means you'll have to create the Alarm instance in the save() function which actually saves the alarm..

**Comment by brittle123** [comment]
Thanks @smfahadhassan
