### ISSUE TITLE
All Alarms are cancelled if i clear ram

### ISSUE THREAD

**Issue by suneelt68** [PPartisan/Simple-Alarms#11]
Hi sir when ever i was clearing RAM in my phone, all the alarms are cancelling, i have tested this scenario by using alarmManager.getNextAlarm method..

**Comment by PPartisan** [comment]
Hello. Could you explain what process it is you're using to "clear ram", and explain what steps I would need to go through to replicate this? Also, what API version are you testing this on. Thanks.

**Comment by PPartisan** [comment]
I haven't been able to replicate this bug myself so I'm closing for now. If I could have the steps to reproduce this problem then I will be happy to reopen this issue.
