### ISSUE TITLE
How to use Filterable

### ISSUE THREAD

**Issue by somoine** [PPartisan/Simple-Alarms#13]
Hello sir.
Is it possible to use a Filterable in  #AlarmsAdapter and if yes how,, because I have tried without any success...

**Comment by PPartisan** [comment]
I haven't tried, but I don't see an issue with using `Filterable` in this app. I'll mark this as a feature request and suggest you make a post in StackOverflow if you have a problem implementing this in your fork. You're welcome to link the question here as well as a comment and I will take a look at it.

**Comment by somoine** [comment]
I was able to achieve it, thank you sir.
