### ISSUE TITLE
alarm setting

### ISSUE THREAD

**Issue by SophieYoonseo** [PPartisan/Simple-Alarms#16]
I set a new alarm and set it to vibrate. I wasn't sure if the alarm went off because the vibration was very short and didn't appear on the screen. So I want to improve the alarm function. 
In addition, I want to add the function to turn off the alarm when I shake my phone.
What do you think of my opinion? Can I try these two things?

**Comment by PPartisan** [comment]
Do you mean that you want to implement these features yourself? You are welcome to if you like, and submit a pull request.

**Comment by SophieYoonseo** [comment]
Ok! After I try this, I will pull request.

**Comment by PPartisan** [comment]
Relates to #17
