### ISSUE TITLE
Alarm Is Not Getting Triggering In Doze Mode

### ISSUE THREAD

**Issue by suneelt68** [PPartisan/Simple-Alarms#8]
Hi sir , i tried to test the application as i need the same requirement what you have done , when the phone is in light doze mode its triggering , but when it is deep doze mode its not triggering , i was using android P .

**Comment by PPartisan** [comment]
I'll look into this soon. In meantime, you could try and experiment with [AlarmManager#setAlarmClock](https://developer.android.com/reference/android/app/AlarmManager.html#setAlarmClock(android.app.AlarmManager.AlarmClockInfo,%20android.app.PendingIntent)) and [AlarmManager#setExactAndAllowWhileIdle](https://developer.android.com/reference/android/app/AlarmManager.html#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)) when setting the Alarm.

**Comment by PPartisan** [comment]
Take a look at PR #9 and see whether it resolves your problem. You can test it on the branch `bugfix/8_no-alarm-in-deep-doze`.
